### ISSUE TITLE
HelloGitHub 反馈收集贴

### ISSUE THREAD

**Issue by 521xueweihan** [521xueweihan/HelloGitHub#673]
## 欢迎提出您的宝贵建议

HG 已经走过了 3 个年头，说来惭愧还没有一个接收用户反馈的地方。经过群里的小伙伴提醒和建议，我们发现了这个问题，所以开了这个“建议、问题收集贴”。

欢迎各位小伙伴，**在此 issue 中回复提出您的宝贵意见**。我们会虚心接受、改正、定期回复，并**整理成 TODO 任务列表**。跟踪、修复问题，增加功能，让大家更好的分享和阅读项目，也欢迎大家**认领任务成为贡献者**。

- [加入我们的讨论群](https://hellogithub.com/weixin.png)
- [点击推荐项目](https://github.com/521xueweihan/HelloGitHub/issues/new)
- [贡献者列表](https://github.com/521xueweihan/HelloGitHub/blob/master/content/contributors.md)

## TODO
- [x] 意见收集入口（issues），更新 README 和 月刊模版，增加反馈入口
- [x] 更新月刊模版，“往期回顾”改成上一期，下一期
- [x] 在简介和项目之间加入项目类别索引
- [ ] 评分系统
- [ ] 月刊 -> 周刊
- [x] 图片加载速度太慢
- [ ] 展示推荐项目的 star 和 fork 数、检测项目链接是否可访问
- [x] 网站每期增加分类目录
- [x] 登陆成功后跳回登陆之前的地址

**Comment by leaicc** [comment]
虽然每一期的下面已经有了『往期回顾』，但还是感觉换成『上一期』、『下一期』的快捷跳转链接更好

**Comment by 521xueweihan** [comment]
> 虽然每一期的下面已经有了『往期回顾』，但还是感觉换成『上一期』、『下一期』的快捷跳转链接更好

嗯，我们记录下来，修改月刊模版的时候，改一下

**Comment by 521xueweihan** [comment]
@leaicc 您好，模版已更新。每期最下面的 “往期回顾”，已经更新为『上一期』、『下一期』。查看地址：https://github.com/521xueweihan/HelloGitHub/blob/master/content/01/HelloGitHub01.md

**Comment by cryzlasm** [comment]
页面有个TOC列表就好了,  对编程语言分门别类,  毕竟不是每个人 都关心每个类别的项目

**Comment by 521xueweihan** [comment]
@cryzlasm 每期已经增加了。但是全部的并未增加，分类查看需要到 https://hellogithub.com 按照分类查看。

**Comment by cryzlasm** [comment]
> @cryzlasm 每期已经增加了。但是全部的并未增加，分类查看需要到 https://hellogithub.com 按照分类查看。

我看见那个分类了,  我看的是最新一期的页面, 比如这个
https://hellogithub.com/periodical/volume/40/

**Comment by 521xueweihan** [comment]
@cryzlasm 好的，明白了。这就安排上

**Comment by zhaojunliing** [comment]
网站图片看不了了

**Comment by 521xueweihan** [comment]
> 网站图片看不了了

收到周末处理，这周工作有点忙

**Comment by 521xueweihan** [comment]
> 网站图片看不了了

@zhaojunliing 感谢反馈，图片已恢复展示（速度可能还有些慢，正在迁移预计下周完成）

**Comment by stevenling** [comment]
可以有 pdf 版本或者 mobi 让 kindle 也能阅读

**Comment by 521xueweihan** [comment]
> 可以有 pdf 版本或者 mobi 让 kindle 也能阅读

OK，此功能会加上去的！

**Comment by 521xueweihan** [comment]
本 issues 停止维护，迁移到 #899 进行维护和回复
